### ISSUE TITLE
Support running arbitrary command

### ISSUE THREAD

**Issue by dotboris** [graze/docker-composer#43]
I've tried to use this image in my CI (gitlab-ci) and I can't get it to work because gitlab-ci spawns a shell on the docker container and then runs commands.

Looking at the `composer-wrapper` script, I see that it's impossible for me to run anything other than composer directly.

**Comment by biggianteye** [comment]
Hi @dotboris. This is intended to be a containerised version of the `composer` command and not a general shell. It's therefore by design that you can't run anything else. Can you give an example of what gitlab-ci is trying to do?

**Comment by dotboris** [comment]
@biggianteye Sorry for the late reply. Turns out that I don't need this anymore. I've been able to work around the issue by setting the entrypoint to `/bin/sh`. (it's an options in gitlab-ci)

**Comment by biggianteye** [comment]
I'm glad you solved your problem.
